### ISSUE TITLE
Strings with more than 100,000 characters seems to hang 

### ISSUE THREAD

**Issue by rbhalla** [davepacheco/node-extsprintf#11]
I am using verror (as part of restify) and have been debugging why our process randomly hangs. It turns out we have an incredibly large error message generated by our database sometimes (around 2mil characters) and the formatting of this message causes it to hang.

I realise this is a limitation of the regex search, but I thought I'd leave an issue here just in case there is a smarter solution that just limiting the error size.

**Comment by davepacheco** [comment]
Is the process actually hung, or just taking a long time to process the string?

**Comment by davepacheco** [comment]
Also, is the long message being used as a format string?  Is that intended?  If it's just the error's message, you could use '%s' as the format string and provide the larger string as the next argument.

**Comment by davepacheco** [comment]
I wrote this test program:

```javascript
$ cat test-long.js 
var mod_assert = require('assert');
var mod_extsprintf = require('./lib/extsprintf');

var printf = mod_extsprintf.printf;
var sprintf = mod_extsprintf.sprintf;

var input, result, tstart, delta;

input = 'abcd';
while (input.length < 100 * 1024) {
	input += input;
}

printf('TEST 1: using large string as an argument\n');
printf('original string length: %d characters\n', input.length);
tstart = process.hrtime();
result = sprintf('>%s<', input);
delta = process.hrtime(tstart);
mod_assert.equal(result, '>' + input + '<');
printf('formatted string length: %d characters\n', result.length);
printf('time: %d.%09d seconds\n', delta[0], delta[1]);

printf('TEST 2: using large string as a format string\n');
printf('original string length: %d characters\n', input.length);
tstart = process.hrtime();
result = sprintf(input);
delta = process.hrtime(tstart);
mod_assert.equal(result, input);
printf('formatted string length: %d characters\n', result.length);
printf('time: %d.%09d seconds\n', delta[0], delta[1]);
```

Here's what I get (on Node v0.10.45 on an early 2013 MacBook Pro, 2.4GHz i7, 16GB DRAM, if anybody cares):

```
$ node test-long.js 
TEST 1: using large string as an argument
original string length: 131072 characters
formatted string length: 131074 characters
time: 0.000051679 seconds
TEST 2: using large string as a format string
original string length: 131072 characters
formatted string length: 131072 characters
time: 18.462315194 seconds
```

So I don't think it was hung -- it just took a while.  This only affects very large format strings, not very large string arguments.  This probably did take a lot longer than it needs to (e.g., compared to if this were implemented without regular expressions), but it's working correctly.  There's nothing wrong with trying to format a 2M character string (as long as you're willing to wait).

If somebody wants to rewrite without regular expressions to improve performance, that'd be fine (assuming we verified the result had the same behavior).
